Skip PR generation if branch for current source commit already exists in downstream repo
stackabletech/operator-templating pull request #103
Opened 2022-03-26 13:18 UTC by soenkeliebau

Check if a branch for the latest commit hash in the templating repo has already been created in downstream repos before attempting to push any changes.

fixes #102

2022-03-26 13:19 UTC, soenkeliebau commented
Full disclosure: this has not been tested, I am unsure how I can test this without merging it :)

2022-03-28 07:40 UTC, siegfriedweber requested changes

2022-03-28 07:40 UTC, siegfriedweber commented on playbook/update_repo.yaml
> +        argv: [git, ls-remote, --exit-code, --heads, https://{{ gh_access_token }}@github.com/{{ operator.url }}, {{ pr_branch_name }}]
```suggestion
        argv: [git, ls-remote, --exit-code, --heads, "https://{{ gh_access_token }}@github.com/{{ operator.url }}", "{{ pr_branch_name }}"]
```

2022-03-28 13:55 UTC, siegfriedweber approved these changes
LGTM

2022-03-29 07:16 UTC, merged